import { MenuItem, MenuCategory } from '@/types/menu';

export const menuCategories: MenuCategory[] = [
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'curry-items', name: 'Curry Items' },
  { id: 'lunch', name: 'Lunch' },
  { id: 'dinner', name: 'Dinner' },
];

// Note: prices are intentionally set to 0, which the UI shows as "Price on request".
// Update the `price` value for any item to enable the add-to-cart flow for it.
export const menuItems: MenuItem[] = [
  // ===== Breakfast =====
  {
    id: '1',
    name: 'Puttu',
    description: 'Steamed cylinders of ground rice layered with grated coconut',
    price: 0,
    category: 'breakfast',
    image: '/menu/puttu.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Traditional', 'Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '2',
    name: 'Poori',
    description: 'Deep-fried puffed wheat bread, served hot',
    price: 0,
    category: 'breakfast',
    image: '/menu/poori.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '3',
    name: 'Vellayappam',
    description: 'Soft, fluffy fermented rice pancakes with a lacy edge',
    price: 0,
    category: 'breakfast',
    image: '/menu/vellayappam.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Traditional', 'Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '4',
    name: 'Idiappam',
    description: 'Steamed string hoppers made from rice flour',
    price: 0,
    category: 'breakfast',
    image: '/menu/idiappam.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Traditional', 'Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '5',
    name: 'Chapathi',
    description: 'Soft, hand-rolled whole wheat flatbread',
    price: 0,
    category: 'breakfast',
    image: '/menu/chapathi.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '6',
    name: 'Porotta',
    description: 'Flaky, layered Malabar flatbread',
    price: 0,
    category: 'breakfast',
    image: '/menu/porotta-breakfast.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Popular', 'Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },

  // ===== Curry Items =====
  {
    id: '7',
    name: 'Egg Curry',
    description: 'Boiled eggs simmered in a spiced Kerala-style gravy',
    price: 0,
    category: 'curry-items',
    image: '/menu/egg-curry.jpeg',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 0,
    tags: ['Egg'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '8',
    name: 'Kadala Curry',
    description: 'Black chickpeas cooked in roasted coconut and spices',
    price: 0,
    category: 'curry-items',
    image: '/menu/kadala-curry.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 0,
    tags: ['Vegetarian', 'Traditional'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '9',
    name: 'Potato Bhaji',
    description: 'Mildly spiced mashed potato side, a classic with poori',
    price: 0,
    category: 'curry-items',
    image: '/menu/potato-bhaji.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 0,
    tags: ['Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '10',
    name: 'Veg Kuruma',
    description: 'Mixed vegetables in a creamy coconut gravy',
    price: 0,
    category: 'curry-items',
    image: '/menu/veg-kuruma.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 0,
    tags: ['Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '11',
    name: 'Chicken Curry',
    description: 'Tender chicken in a traditional Kerala spiced gravy',
    price: 0,
    category: 'curry-items',
    image: '/menu/chicken-curry.jpeg',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 0,
    tags: ['Non-Veg'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },

  // ===== Lunch =====
  {
    id: '12',
    name: 'Meals',
    description: 'Wholesome Kerala rice meals served with assorted sides',
    price: 0,
    category: 'lunch',
    image: '/menu/meals.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Traditional', 'Value'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '13',
    name: 'Sadya',
    description: 'Traditional Kerala feast served on a banana leaf',
    price: 0,
    category: 'lunch',
    image: '/menu/sadya.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Traditional', 'Festival Special'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '14',
    name: 'Biriyani',
    description: 'Aromatic basmati rice layered with spices, our signature dish',
    price: 0,
    category: 'lunch',
    image: '/menu/biriyani.jpeg',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: true,
    spiceLevel: 'medium',
    preparationTime: 0,
    tags: ['Signature', 'Bestseller'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '15',
    name: 'Ghee Rice',
    description: 'Fragrant rice cooked in ghee with whole spices',
    price: 0,
    category: 'lunch',
    image: '/menu/ghee-rice.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '16',
    name: 'Porotta',
    description: 'Flaky, layered Malabar flatbread, perfect with any curry',
    price: 0,
    category: 'lunch',
    image: '/menu/porotta-lunch.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Popular', 'Vegetarian'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },
  {
    id: '17',
    name: 'Chicken Fry',
    description: 'Crisp, spiced fried chicken, Kerala style',
    price: 0,
    category: 'lunch',
    image: '/menu/chicken-fry.jpeg',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 0,
    tags: ['Non-Veg', 'Popular'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  },

  // ===== Dinner =====
  {
    id: '18',
    name: 'Made to Order',
    description: 'We prepare dinner fresh according to your order. Call us to let us know what you would like.',
    price: 0,
    category: 'dinner',
    image: '/menu/porotta-lunch.jpeg',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 0,
    tags: ['Fresh', 'Custom'],
    rating: 0,
    reviewCount: 0,
    orderCount: 0
  }
];
