import { MenuItem, MenuCategory } from '@/types/menu';

export const menuCategories: MenuCategory[] = [
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'lunch-specials', name: 'Lunch Specials' },
  { id: 'dinner', name: 'Dinner' },
  { id: 'biryani', name: 'Biryani' },
  { id: 'traditional-sadhya', name: 'Traditional Sadhya' },
  { id: 'dosa-varieties', name: 'Dosa Varieties' },
  { id: 'chapathi-porotta', name: 'Chapathi & Porotta' },
  { id: 'curry-items', name: 'Curry Items' },
  { id: 'river-fish', name: 'River Fish' },
  { id: 'daily-specials', name: 'Daily Specials' },
  { id: 'beverages', name: 'Beverages' },
  { id: 'desserts', name: 'Desserts' },
  { id: 'snacks', name: 'Snacks' },
];

export const menuItems: MenuItem[] = [
  // Breakfast Items
  {
    id: '1',
    name: 'Appam with Stew',
    description: 'Soft, fluffy rice pancakes served with vegetable or chicken stew',
    price: 60,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 15,
    tags: ['Traditional', 'Healthy'],
    rating: 4.6,
    reviewCount: 145,
    orderCount: 523
  },
  {
    id: '2',
    name: 'Puttu with Kadala Curry',
    description: 'Steamed rice cylinder served with spiced black chickpea curry',
    price: 50,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 20,
    tags: ['Traditional', 'Protein Rich'],
    rating: 4.7,
    reviewCount: 189,
    orderCount: 612
  },
  {
    id: '3',
    name: 'Idli Sambar',
    description: 'Steamed rice cakes served with lentil soup and chutneys',
    price: 40,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 10,
    tags: ['Healthy', 'Light'],
    rating: 4.5,
    reviewCount: 234,
    orderCount: 789
  },

  // Biryani
  {
    id: '4',
    name: 'Special Chicken Biryani',
    description: 'Our signature dish - aromatic basmati rice layered with tender chicken, infused with authentic Kerala spices',
    price: 180,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: true,
    spiceLevel: 'medium',
    preparationTime: 45,
    tags: ['Signature', 'Bestseller'],
    rating: 4.8,
    reviewCount: 567,
    orderCount: 2341
  },
  {
    id: '5',
    name: 'Mutton Biryani',
    description: 'Premium quality mutton cooked with fragrant rice and special spices',
    price: 220,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'hot',
    preparationTime: 60,
    tags: ['Premium', 'Spicy'],
    rating: 4.7,
    reviewCount: 423,
    orderCount: 1567
  },
  {
    id: '6',
    name: 'Vegetable Biryani',
    description: 'Mixed vegetables and paneer cooked with aromatic rice',
    price: 140,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 35,
    tags: ['Vegetarian', 'Healthy'],
    rating: 4.4,
    reviewCount: 234,
    orderCount: 890
  },

  // Traditional Sadhya
  {
    id: '7',
    name: 'Nadan Sadhya (Full)',
    description: 'Traditional Kerala feast served on banana leaf with 20+ items including rice, sambar, rasam, avial, thoran, pachadi, and payasam',
    price: 250,
    category: 'traditional-sadhya',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 30,
    tags: ['Traditional', 'Festival Special'],
    rating: 4.9,
    reviewCount: 789,
    orderCount: 3456
  },
  {
    id: '8',
    name: 'Mini Sadhya',
    description: 'Smaller portion of traditional feast with 10 essential items',
    price: 150,
    category: 'traditional-sadhya',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 20,
    tags: ['Traditional', 'Value'],
    rating: 4.7,
    reviewCount: 456,
    orderCount: 2134
  },

  // Dosa Varieties
  {
    id: '9',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato filling, served with sambar and chutneys',
    price: 80,
    category: 'dosa-varieties',
    image: 'https://images.unsplash.com/photo-1630383249904-fc01cc4d1dc4?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 20,
    tags: ['Popular', 'Crispy'],
    rating: 4.5,
    reviewCount: 567,
    orderCount: 2890
  },
  {
    id: '10',
    name: 'Ghee Roast Dosa',
    description: 'Paper-thin crispy dosa roasted in pure ghee',
    price: 90,
    category: 'dosa-varieties',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 15,
    tags: ['Premium', 'Crispy'],
    rating: 4.6,
    reviewCount: 345,
    orderCount: 1567
  },

  // River Fish
  {
    id: '11',
    name: 'Karimeen Fry',
    description: 'Pearl spot fish marinated in traditional spices and shallow fried',
    price: 280,
    category: 'river-fish',
    image: 'https://images.unsplash.com/photo-1626200419320-77448f03151d?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: true,
    spiceLevel: 'medium',
    preparationTime: 25,
    tags: ['Fresh Catch', 'Specialty'],
    rating: 4.8,
    reviewCount: 456,
    orderCount: 1890
  },
  {
    id: '12',
    name: 'Fish Curry Meals',
    description: 'Traditional Kerala fish curry served with rice, vegetables, and accompaniments',
    price: 120,
    category: 'river-fish',
    image: 'https://images.unsplash.com/photo-1596128160992-bd90fb59f190?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 30,
    tags: ['Traditional', 'Meal'],
    rating: 4.7,
    reviewCount: 678,
    orderCount: 3234
  },

  // Curry Items
  {
    id: '13',
    name: 'Kerala Beef Curry',
    description: 'Tender beef cooked in aromatic spices with coconut',
    price: 150,
    category: 'curry-items',
    image: 'https://images.unsplash.com/photo-1670163090584-e43596b4471f?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'hot',
    preparationTime: 40,
    tags: ['Spicy', 'Traditional'],
    rating: 4.6,
    reviewCount: 345,
    orderCount: 1456
  },
  {
    id: '14',
    name: 'Chicken Varutharachathu',
    description: 'Chicken curry with roasted coconut and spices',
    price: 140,
    category: 'curry-items',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'medium',
    preparationTime: 35,
    tags: ['Traditional', 'Coconut'],
    rating: 4.7,
    reviewCount: 456,
    orderCount: 2123
  },

  // Chapathi & Porotta
  {
    id: '15',
    name: 'Kerala Porotta with Beef Curry',
    description: 'Flaky, layered porotta served with spicy beef curry',
    price: 150,
    category: 'chapathi-porotta',
    image: 'https://images.unsplash.com/photo-1670163090584-e43596b4471f?w=600&h=400&fit=crop',
    isVegetarian: false,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'hot',
    preparationTime: 35,
    tags: ['Popular', 'Combo'],
    rating: 4.8,
    reviewCount: 789,
    orderCount: 4567
  },
  {
    id: '16',
    name: 'Chapathi with Vegetable Kurma',
    description: 'Soft wheat chapathi served with mixed vegetable kurma',
    price: 80,
    category: 'chapathi-porotta',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    spiceLevel: 'mild',
    preparationTime: 20,
    tags: ['Healthy', 'Vegetarian'],
    rating: 4.4,
    reviewCount: 234,
    orderCount: 1234
  },

  // Beverages
  {
    id: '17',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime soda with mint',
    price: 30,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1523371054106-bbf80586c38c?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 5,
    tags: ['Refreshing', 'Cold'],
    rating: 4.5,
    reviewCount: 567,
    orderCount: 3456
  },
  {
    id: '18',
    name: 'Filter Coffee',
    description: 'Strong South Indian filter coffee',
    price: 25,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 5,
    tags: ['Hot', 'Traditional'],
    rating: 4.7,
    reviewCount: 890,
    orderCount: 5678
  },
  {
    id: '19',
    name: 'Sambaram (Buttermilk)',
    description: 'Traditional spiced buttermilk with curry leaves',
    price: 20,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1571091655789-405eb7a3a3a8?w=600&h=400&fit=crop',
    isVegetarian: true,
    isAvailable: true,
    isDailySpecial: false,
    preparationTime: 5,
    tags: ['Traditional', 'Healthy'],
    rating: 4.6,
    reviewCount: 456,
    orderCount: 2345
  }
];
